import { useEffect, useMemo, useState } from "react";
import { BarChart3, Calculator, Eye, MousePointerClick, UserRoundCheck } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../api";
import type { AnalyticsData } from "../types";
import { EmptyState, LoadingBlock } from "../ui";

const eventLabels: Record<string, string> = { page_view: "Visitas", calculator_selected: "Eligieron cálculo", calculation_started: "Comenzaron", calculation_completed: "Vieron resultado", lead_created: "Dejaron datos", whatsapp_clicked: "Abrieron WhatsApp", appointment_intent: "Quisieron agendar" };

export default function Metrics({ refreshKey }: { refreshKey: number }) {
  const [data, setData] = useState<AnalyticsData | null>(null); const [days, setDays] = useState(30); const [error, setError] = useState("");
  useEffect(() => { setData(null); api<AnalyticsData>(`/api/analytics?days=${days}`).then(setData).catch(caught => setError(caught instanceof Error ? caught.message : "No fue posible cargar las métricas.")); }, [days, refreshKey]);
  const totals = useMemo(() => new Map(data?.totals.map(item => [item.event_type, item.total]) || []), [data]);
  const chart = useMemo(() => { const map = new Map<string, { day: string; visitas: number; resultados: number; prospectos: number }>(); for (const row of data?.daily || []) { const current = map.get(row.day) || { day: row.day, visitas: 0, resultados: 0, prospectos: 0 }; if (row.event_type === "page_view") current.visitas += row.total; if (row.event_type === "calculation_completed") current.resultados += row.total; if (row.event_type === "lead_created") current.prospectos += row.total; map.set(row.day, current); } return [...map.values()]; }, [data]);
  const visits = totals.get("page_view") || 0; const results = totals.get("calculation_completed") || 0; const leads = totals.get("lead_created") || 0; const appointments = totals.get("appointment_intent") || 0;
  const pct = (value: number, base: number) => base ? `${Math.round(value / base * 1000) / 10}%` : "0%";
  return <div className="page-stack">
    <section className="page-heading"><div><span className="eyebrow">De atención a conversación</span><h1>Métricas de la <em>landing</em></h1><p>Descubre cuántas personas avanzan desde una visita hasta dejar sus datos.</p></div><select value={days} onChange={event => setDays(Number(event.target.value))}><option value={7}>Últimos 7 días</option><option value={30}>Últimos 30 días</option><option value={90}>Últimos 90 días</option><option value={365}>Último año</option></select></section>
    {error && <div className="notice notice--error">{error}</div>}
    {!data ? <LoadingBlock /> : <>
      <section className="metric-grid"><article className="metric-card metric-card--accent"><span>Visitas</span><strong>{visits}</strong><small><Eye size={14} /> Personas que entraron</small></article><article className="metric-card"><span>Resultados vistos</span><strong>{results}</strong><small><Calculator size={14} /> {pct(results, visits)} de las visitas</small></article><article className="metric-card"><span>Datos recibidos</span><strong>{leads}</strong><small><UserRoundCheck size={14} /> {pct(leads, visits)} de conversión</small></article><article className="metric-card"><span>Intención de cita</span><strong>{appointments}</strong><small><MousePointerClick size={14} /> {pct(appointments, visits)} de las visitas</small></article></section>
      <section className="metrics-layout">
        <article className="panel chart-panel"><header className="panel__header"><div><span className="eyebrow">Actividad diaria</span><h2>Cómo avanza el interés</h2></div></header>{chart.length ? <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="visitFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#623773" stopOpacity={0.28}/><stop offset="95%" stopColor="#623773" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#ece5e0" vertical={false}/><XAxis dataKey="day" tickFormatter={value => new Intl.DateTimeFormat("es-MX", { day: "numeric", month: "short" }).format(new Date(`${value}T12:00:00`))} axisLine={false} tickLine={false} fontSize={11}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} fontSize={11}/><Tooltip labelFormatter={value => new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(`${value}T12:00:00`))}/><Area type="monotone" dataKey="visitas" stroke="#623773" fill="url(#visitFill)" strokeWidth={2}/><Area type="monotone" dataKey="resultados" stroke="#a57591" fill="transparent" strokeWidth={2}/><Area type="monotone" dataKey="prospectos" stroke="#c18b4a" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div> : <EmptyState icon={<BarChart3 size={26} />} title="Aún no hay actividad medida" copy="Las visitas y acciones aparecerán cuando conectemos la landing al CRM." />}</article>
        <article className="panel funnel-panel"><header><span className="eyebrow">Embudo de la página</span><h2>Del interés al contacto</h2></header><div className="funnel-list">{["page_view", "calculator_selected", "calculation_started", "calculation_completed", "lead_created", "appointment_intent"].map((event, index, list) => { const total = totals.get(event) || 0; const prior = index ? totals.get(list[index - 1]) || 0 : total; return <div className="funnel-item" key={event}><span style={{ width: `${Math.max(4, visits ? total / visits * 100 : 0)}%` }} /><div><strong>{total}</strong><small>{eventLabels[event]}</small></div>{index > 0 && <i>{pct(total, prior)}</i>}</div>; })}</div><p className="panel-note">Las cifras comienzan a registrarse desde el momento en que la landing se conecta; no reconstruyen visitas anteriores.</p></article>
      </section>
    </>}
  </div>;
}
